version: '3'
services:
  app:
    container_name: webapp
    build: .
    ports:
      - 8080:8080
    restart: on_failure
    volumes: 
      - .:/app
    depends_on: 
      - postgresapp
    networks: 
      - devenv
  postgresapp:
    container_name: psqldb
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      - devenv

  networks:
    devenv:
      driver: bridge
